name: Mein Erster Workflow

on:
  push:
    branches:
      - main

jobs:
  mein_erster_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Hallo Welt Nachricht
        run: echo "Hallo von meinem ersten GitHub Actions Job!"

      - name: Zeige aktuelles Datum und Uhrzeit
        run: date
