name: Mein Erweiterter Workflow

on: [push, pull_request]

jobs:
  mein_erster_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Hallo Welt Nachricht
        run: echo "Hallo von meinem ersten GitHub Actions Job!"

      - name: Zeige aktuelles Datum und Uhrzeit
        run: date

  mein_zweiter_job:
    runs-on: ubuntu-latest
    needs: mein_erster_job # Dieser Job wird erst ausgeführt, nachdem 'mein_erster_job' erfolgreich war.

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Python vorbereiten
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Du kannst hier eine spezifische Python-Version angeben

      - name: Simuliere ein Python-Skript
        run: |
          echo "print('Dies ist ein simuliertes Python-Skript.')" > mein_skript.py
          python mein_skript.py

      - name: Erfolgreich abgeschlossen
        run: echo "Der zweite Job wurde erfolgreich ausgeführt!"
